APP_NAME = "rife"
CONFIG_PATH = f"/etc/{APP_NAME}/"
PACKAGE_DB_PATH = f"/home/hakai/Project/Rife/test/Package.db"
PACKAGE_PATH = f"/var/lib/{APP_NAME}/"
SOURCE_LIST = f"{APP_NAME}_sources.list"
PKG_GZ_DOWNLOAD_PATH = f"/tmp/{APP_NAME}/package/"
DEFAULT_MIRROR = "deb http://http.kali.org/kali kali-rolling main contrib non-free"
