APP_NAME = "rife"
CONFIG_PATH = f"/etc/{APP_NAME}/"
PACKAGE_PATH = f"/var/lib/{APP_NAME}/"
PACKAGE_DB_PATH = f"{PACKAGE_PATH}Package.db"
SOURCE_LIST = f"{APP_NAME}_sources.list"
PKG_GZ_DOWNLOAD_PATH = f"/tmp/{APP_NAME}/package/"
PKG_DOWNLOAD_PATH = f"/tmp/{APP_NAME}/download/"
DEFAULT_MIRROR = "deb http://http.kali.org/kali kali-rolling main contrib non-free"
